CiscoSystems\DirectoryBundle\Entity\Session:
    type: entity
    table: directory__session
    id:
        sessionId:
            type: string
            column: session_id
            type: string
    fields:
        value:
            column: session_value
            type: text
        time:
            column: session_time
            type: integer