CiscoSystems\DirectoryBundle\Entity\User:
    type: mappedSuperClass
    fields:
#        foo:
#            column: foo
#            type: string
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create