parameters:
    cisco.ldap.storageagnostic_objectmanager.class: CiscoSystems\DirectoryBundle\Model\StorageAgnosticObjectManager
    cisco.ldap.user.class:                          CiscoSystems\DirectoryBundle\Entity\User
    cisco.ldap.session.class:                       CiscoSystems\DirectoryBundle\Entity\Session

services:
    cisco.ldap.user_manager:
        class: '%cisco.ldap.storageagnostic_objectmanager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%cisco.ldap.user.class%'
    cisco.ldap.session_manager:
        class: '%cisco.ldap.storageagnostic_objectmanager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%cisco.ldap.session.class%'