parameters:
    cisco.ldap.directory_manager.class:  CiscoSystems\DirectoryBundle\Directory\DirectoryManager
    cisco.ldap.base_repository.class:    CiscoSystems\DirectoryBundle\Directory\QueryRepository
    cisco.ldap.authentication_provider.class: CiscoSystems\DirectoryBundle\Authentication\DirectoryAuthenticationProvider
#    cisco.ldap.configuration: ~

services:
    # Directory manager
    cisco.ldap:
        class: '%cisco.ldap.directory_manager.class%'
        arguments:
            - '%cisco.ldap.configuration%'
            - '%cisco.ldap.base_repository.class%'
    # Authentication provider
    cisco.ldap.authentication_provider:
        class: '%cisco.ldap.authentication_provider.class%'
        arguments:
            - ''
            - '@cisco.ldap'
            - '%cisco.ldap.configuration%'
            - '@logger'