parameters:
    cisco.ldap.directory_manager.class:       CiscoSystems\DirectoryBundle\Directory\DirectoryManager
    cisco.ldap.base_repository.class:         CiscoSystems\DirectoryBundle\Directory\QueryRepository
    cisco.ldap.authenticator.class:           CiscoSystems\DirectoryBundle\Authentication\DirectoryAuthenticator

services:
# Directory manager
    cisco.ldap:
        class: '%cisco.ldap.directory_manager.class%'
        arguments:
            - '%cisco.ldap.configuration%'
            - '%cisco.ldap.base_repository.class%'
            - '@security.token_storage'

# Authenticator - see http://symfony.com/doc/current/cookbook/security/custom_password_authenticator.html
    cisco.ldap.authenticator:
        class: '%cisco.ldap.authenticator.class%'
        arguments:
            - '@cisco.ldap'
            - '@logger'