CiscoSystems\DirectoryBundle\Model\User:
    type: mappedSuperClass
    fields:
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create